<?php

namespace App\Filament\Resources\Orders\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class OrderInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('public_id'),
                TextEntry::make('user.name')
                    ->label('User'),
                TextEntry::make('providerProfile.id')
                    ->label('Provider profile')
                    ->placeholder('-'),
                TextEntry::make('service.name')
                    ->label('Service')
                    ->placeholder('-'),
                TextEntry::make('serviceTier.name')
                    ->label('Service tier')
                    ->placeholder('-'),
                TextEntry::make('transportZone.name')
                    ->label('Transport zone')
                    ->placeholder('-'),
                TextEntry::make('status')
                    ->badge(),
                TextEntry::make('booking_mode')
                    ->badge(),
                TextEntry::make('pair_provider_number')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('service_name_snapshot')
                    ->placeholder('-'),
                TextEntry::make('service_tier_name_snapshot')
                    ->placeholder('-'),
                TextEntry::make('transport_zone_name_snapshot')
                    ->placeholder('-'),
                IconEntry::make('is_scheduled')
                    ->boolean(),
                TextEntry::make('scheduled_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('offering_started_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('accepted_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('on_the_way_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('arrived_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('in_service_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('completed_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('cancelled_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('expired_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('cancelled_by_user_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('cancellation_reason')
                    ->placeholder('-'),
                TextEntry::make('cancellation_fee_amount')
                    ->numeric(),
                TextEntry::make('address_text'),
                TextEntry::make('location_lat')
                    ->numeric(),
                TextEntry::make('location_lng')
                    ->numeric(),
                TextEntry::make('provider_last_location_lat')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('provider_last_location_lng')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('provider_last_location_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('provider_eta_minutes')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('provider_distance_meters')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('place_id')
                    ->placeholder('-'),
                TextEntry::make('payment_method')
                    ->badge(),
                TextEntry::make('payment_status')
                    ->badge(),
                TextEntry::make('paid_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('subtotal_amount')
                    ->numeric(),
                TextEntry::make('transport_fee_amount')
                    ->numeric(),
                TextEntry::make('distance_fee_amount')
                    ->numeric(),
                TextEntry::make('overtime_fee_amount')
                    ->numeric(),
                TextEntry::make('peak_fee_amount')
                    ->numeric(),
                TextEntry::make('tax_amount')
                    ->numeric(),
                TextEntry::make('discount_amount')
                    ->numeric(),
                TextEntry::make('total_amount')
                    ->numeric(),
                TextEntry::make('promo_code')
                    ->placeholder('-'),
                TextEntry::make('provider_rating')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('provider_review')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('rated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
