<?php

namespace App\Filament\Resources\Orders\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Actions\ViewAction;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class OrdersTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('public_id')
                    ->searchable(),
                TextColumn::make('user.name')
                    ->searchable(),
                TextColumn::make('providerProfile.id')
                    ->searchable(),
                TextColumn::make('service.name')
                    ->searchable(),
                TextColumn::make('serviceTier.name')
                    ->searchable(),
                TextColumn::make('transportZone.name')
                    ->searchable(),
                TextColumn::make('status')
                    ->badge()
                    ->searchable(),
                TextColumn::make('booking_mode')
                    ->badge()
                    ->searchable(),
                TextColumn::make('pair_provider_number')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('service_name_snapshot')
                    ->searchable(),
                TextColumn::make('service_tier_name_snapshot')
                    ->searchable(),
                TextColumn::make('transport_zone_name_snapshot')
                    ->searchable(),
                IconColumn::make('is_scheduled')
                    ->boolean(),
                TextColumn::make('scheduled_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('offering_started_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('accepted_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('on_the_way_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('arrived_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('in_service_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('completed_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('cancelled_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('expired_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('cancelled_by_user_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('cancellation_reason')
                    ->searchable(),
                TextColumn::make('cancellation_fee_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('address_text')
                    ->searchable(),
                TextColumn::make('location_lat')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('location_lng')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('provider_last_location_lat')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('provider_last_location_lng')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('provider_last_location_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('provider_eta_minutes')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('provider_distance_meters')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('place_id')
                    ->searchable(),
                TextColumn::make('payment_method')
                    ->badge()
                    ->searchable(),
                TextColumn::make('payment_status')
                    ->badge()
                    ->searchable(),
                TextColumn::make('paid_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('subtotal_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('transport_fee_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('distance_fee_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('overtime_fee_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('peak_fee_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('tax_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('discount_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('total_amount')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('promo_code')
                    ->searchable(),
                TextColumn::make('provider_rating')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('rated_at')
                    ->dateTime()
                    ->sortable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                ViewAction::make(),
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
